apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kafka
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "4"
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: streaming
  source:
    repoURL: https://github.com/<your-account>/data-platform-poc.git
    targetRevision: main
    path: platform/components/kafka
    directory:
      recurse: true
      exclude: '{*values*.yaml,README.md}'
  syncPolicy:
    syncOptions: [CreateNamespace=true, ServerSideApply=true]
